local must be a function in ksh because sourced command execution is delayed. http://www2.research.att.com/sw/download/man/man1/ksh.html "The built-in command  . file  reads the whole file before any commands are executed. Therefore, alias and unalias commands in the file will not apply to any commands defined in the file."

diff --git a/env b/env
--- a/env
+++ b/env
@@ -11,11 +11,17 @@ if ! type local >/dev/null 2>&1
 then
 	if type typeset >/dev/null 2>&1
 	then
-		echo creating local alias
-		alias local='typeset'
-	else
-		echo "Cannot find local or typeset shell command, some features in .shrc will not work" 1>&2
-	fi
+        # must be a function not an alias so it works in ksh too
+        local()
+        {
+            typeset "$@"
+        }
+    fi
+    # see if our attempts to emulate "local" worked
+    if ! type local >/dev/null 2>&1
+    then
+        echo "Cannot find local or typeset shell command, some features in .shrc will not work" 1>&2
+    fi
 fi
 
 ### HELPER FUNCTIONS
