If the shell is being run as sh or dash, return early without starting shpool or doing anything else fancy
This provides a failsafe way of connecting if somehow the nice stuff breaks.

Yes, returning from an rc file works.

diff --git a/shrc b/shrc
--- a/shrc
+++ b/shrc
@@ -28,9 +28,27 @@ is_bash() {
     [ -n "${BASH_VERSION:-}" ]
 }
 
+is_dash() {
+    test "$0" = "dash"
+}
+
 is_ksh() {
     [ -n "${KSH_VERSION:-}" ]
 }
+
+is_sh() {
+    test "$0" = "sh"
+}
+
+if is_sh || is_dash; then
+    # If connecting to this machine by running sh or dash, skip all of the
+    # complex stuff below.
+    # This provides a failsafe in case something is broken.
+    echo basic mode >&2
+    PS1="
+$(basename "$PWD")$ "
+    return
+fi
 
 if is_zsh; then
     shell=zsh
